### ISSUE TITLE
unable to install 

### ISSUE THREAD

**Issue by kunaljaani** [IGBB/egads#3]
Hi!

I recently came across your article and found the “egads” very interesting and was hoping to implement it in my study.  I was trying to install it as per the description but it gave the following error upon running the make command.

main.c:9:10: fatal error: klib/kseq.h: No such file or directory
    9 | #include "klib/kseq.h"
![error_1]

      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: main.o] Error 1

Can you please suggest some solution?

Thanks a lot.
Kunal
(https://user-images.githubusercontent.com/31530817/219697625-826195ff-b927-4ae7-9623-baa435d4c99d.png)

**Comment by maa146** [comment]
Does the file `src/klib/klib.h` exist? If not, the klib submodule wasn't cloned. You should be able to run`git submodule update --init` in the egads folder to fix it.

**Comment by kunaljaani** [comment]
Hi Tony,

Thanks for your rapid response. 

Ya the klib.h was missing. After the running git submodule update --init, the folder src/klib has multiple folders and files but still missing src/klib/**klib.h**. and also getting the error upon running the make command.

Thanks for your time and help.
Kunal


gcc -o ../egads -Wall -O3  -lm -ggdb -lz main.o restrict.o enzyme.o sequence.o counts.o html.o d3.bin.o css.bin.o html.bin.o gel.bin.o ridge.bin.o table.bin.o msbuffmin.bin.o args.o
/usr/bin/ld: main.o: in function `ks_getuntil2':
/home/kunal_j/uulm/egads/src/main.c:14: undefined reference to `gzread'
/usr/bin/ld: main.o: in function `main':
/home/kunal_j/uulm/egads/src/main.c:49: undefined reference to `gzopen'
/usr/bin/ld: main.o: in function `ks_getc':
/home/kunal_j/uulm/egads/src/main.c:14: undefined reference to `gzread'
/usr/bin/ld: main.o: in function `ks_getuntil2':
/home/kunal_j/uulm/egads/src/main.c:14: undefined reference to `gzread'
/usr/bin/ld: main.o: in function `main':
/home/kunal_j/uulm/egads/src/main.c:58: undefined reference to `log10'
/usr/bin/ld: /home/kunal_j/uulm/egads/src/main.c:58: undefined reference to `round'
/usr/bin/ld: main.o: in function `ks_getc':
/home/kunal_j/uulm/egads/src/main.c:14: undefined reference to `gzread'
/usr/bin/ld: /home/kunal_j/uulm/egads/src/main.c:14: undefined reference to `gzread'
/usr/bin/ld: main.o: in function `main':
/home/kunal_j/uulm/egads/src/main.c:131: undefined reference to `gzclose'
collect2: error: ld returned 1 exit status
make: *** [makefile:45: ../egads] Error 1

**Comment by maa146** [comment]
Sorry Kunal, I misdiagnosed the issue. It should be able compile now if you pull the latest commit, or you can run the following in the src directory:
```
gcc -o ../egads -Wall -O3  main.o restrict.o enzyme.o sequence.o counts.o html.o d3.bin.o css.bin.o html.bin.o gel.bin.o ridge.bin.o table.bin.o msbuffmin.bin.o args.o -lm -lz
```
