### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by BrunoBertolasi** [IGBB/egads#4]
Hello,
I read with interest your article and your script seems to me very useful in testing some preliminary in silica digestions for my project. 
By the way I have some problems with installation and I got this error message:

(base) bruno@Pleroma:~/Desktop$ make -C egads/src
make: Entering directory '/home/bruno/Desktop/egads/src'
gcc -o ../egads -Wall -O3  -lm -ggdb -lz main.o restrict.o enzyme.o sequence.o counts.o html.o d3.bin.o css.bin.o html.bin.o gel.bin.o ridge.bin.o table.bin.o msbuffmin.bin.o args.o
/usr/bin/ld: warning: msbuffmin.bin.o: missing .note.GNU-stack section implies executable stack
/usr/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
/usr/bin/ld: main.o: in function `ks_getuntil2':
/home/bruno/Desktop/egads/src/main.c:14: undefined reference to `gzread'
/usr/bin/ld: main.o: in function `main':
/home/bruno/Desktop/egads/src/main.c:49: undefined reference to `gzopen'
/usr/bin/ld: main.o: in function `ks_getc':
/home/bruno/Desktop/egads/src/main.c:14: undefined reference to `gzread'
/usr/bin/ld: main.o: in function `ks_getuntil2':
/home/bruno/Desktop/egads/src/main.c:14: undefined reference to `gzread'
/usr/bin/ld: main.o: in function `main':
/home/bruno/Desktop/egads/src/main.c:131: undefined reference to `gzclose'
/usr/bin/ld: main.o: in function `ks_getc':
/home/bruno/Desktop/egads/src/main.c:14: undefined reference to `gzread'
/usr/bin/ld: /home/bruno/Desktop/egads/src/main.c:14: undefined reference to `gzread'
/usr/bin/ld: main.o: in function `main':
/home/bruno/Desktop/egads/src/main.c:58: undefined reference to `log10'
/usr/bin/ld: /home/bruno/Desktop/egads/src/main.c:58: undefined reference to `round'
collect2: error: ld returned 1 exit status
make: *** [makefile:45: ../egads] Error 1
make: Leaving directory '/home/bruno/Desktop/egads/src'

I currently have Ubuntu 23.04 version installed. 
Do you have any suggest? Thanks in advance.

    Bruno

**Comment by maa146** [comment]
Can you run the following as a test? It should finish the build process and produce the executable `/home/bruno/Desktop/egads/egads`.
```
cd /home/bruno/Desktop/egads/src
gcc -o ../egads -Wall -O3 main.o restrict.o enzyme.o sequence.o counts.o html.o d3.bin.o css.bin.o html.bin.o gel.bin.o ridge.bin.o table.bin.o msbuffmin.bin.o args.o -lm -lz
```

I believe the issue is the newer version of gcc is more pedantic regarding library include positions. Please let me know if it works and I'll update the makefile accordingly.

Tony

**Comment by BrunoBertolasi** [comment]
Hello Tony,
Thanks a lot for your very quick answer! I performed the test but it seems not to be effective:

(base) bruno@Pleroma:~/Desktop/egads/src$ gcc -o ../egads -Wall -O3 main.o restrict.o enzyme.o sequence.o counts.o html.o d3.bin.o css.bin.o html.bin.o gel.bin.o ridge.bin.o table.bin.o msbuffmin.bin.o args.o -lm -lz
/usr/bin/ld: warning: msbuffmin.bin.o: missing .note.GNU-stack section implies executable stack
/usr/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker

**Comment by maa146** [comment]
If that's the the only output, then it was probably successful. 

Do you have the executable `/home/bruno/Desktop/egads/egads`?

**Comment by BrunoBertolasi** [comment]
Hello Tony,
I found the executable so installation was successful. 
How to start to use the program? I understood the syntax, but should I add my reference genome in a specific folder of the installation, or is possible use the absolute path? Is there a pre defined list of RE from which can I choose? Data in /test/data seem to be already elaborated: is there any row data anywhere in order to perform a quick test?
Thanks.

  Bruno

**Comment by maa146** [comment]
I've update the readme to include a full example (recreates the report used in the paper). 

Any path (absolute or relative) to a file should work for both the input fasta file and the output html and/or bed file

The REs are defined in REBASE. I've now included links in the readme. 

The test folder are unit test to validate some of the code, not to test if the program compiled correctly. To do that run the example in the updated readme. Sorry for the confusion.

**Comment by BrunoBertolasi** [comment]
Hello Tony,
I've tried with the example and all went smooth. 
Thanks again for your kind help and explanations.

   Bruno
